version: '3.8'

services:
  postgres_db:
    container_name: dev_postgres_db
    image: postgres:13-alpine
    ports: 
      - ${PG_PORT}:${PG_PORT}
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    networks:
      - dev_network
    volumes:
      - dev_pg_data:/var/lib/postgresql/data/
    restart: always

  server: 
    container_name: dev_server
    build:
      context: .
      target: dev
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - 2345:2345
    networks:
      - dev_network
    depends_on:
      - postgres_db
    volumes:
      - .:/app:rw,delegated
    restart: always

networks:
  dev_network:
    name: dev_network

volumes:
  dev_pg_data: