version: '3.8'

services:
  postgres_db:
    container_name: dev_postgres_db
    image: postgres:13-alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    networks:
      - dev_network
    volumes:
      - dev_pg_data:/var/lib/postgresql/data/
    restart: always

  server: 
    container_name: dev_server
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
      - 2345:2345
    networks:
      - dev_network
    depends_on:
      - postgres_db
    volumes:
      - .:/app:rw,delegated
    restart: always

networks:
  dev_network:
    name: dev_network

volumes:
  dev_pg_data: